apiVersion: v1
kind: Service
metadata:
  name: gx-fma-portal
  namespace: gx-lab
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http-api
  selector:
    app: gx-fma-portal
  type: LoadBalancer
