apiVersion: apps/v1
kind: Deployment
metadata:
  name: gx-fma-portal
  namespace: gx-lab
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gx-fma-portal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gx-fma-portal
    spec:
      containers:
        - image: vdxcontainerregistry2022051200.azurecr.io/gx-fma-portal:v1.0.0
          imagePullPolicy: Always
          name: gx-fma-portal
          ports:
            - containerPort: 8000
              name: http-api
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
